// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: internal/distree/proto/distree.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PutStreamReq 是每次发送的消息，首条包含元数据和首块 body，
// 后续条目只需携带 body（其余字段留空即可，服务端以首条元数据为准）。
type PutStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件名（basename）
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 当前 body 块的 MD5，用于逐块校验
	Md5 string `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	// 目标目录（远端落盘路径，服务端将文件保存为 dest_dir/name）
	DestDir string `protobuf:"bytes,3,opt,name=dest_dir,json=destDir,proto3" json:"dest_dir,omitempty"`
	// 文件内容块
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// 下一跳及后续节点列表（逗号或 nodeset 表达式，如 "cn2,cn3" 或 "cn[2-3]"）
	// 服务端收到后按 width 分组建立下游流，并将各子集继续下传
	Nodelist string `protobuf:"bytes,5,opt,name=nodelist,proto3" json:"nodelist,omitempty"`
	// 下游 agent 监听端口（默认值；若环境变量 TRANS_TOOLS_NODE_PORTS 中有对应节点则以环境变量为准）
	Port string `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
	// 树宽：每个中间节点最多向 width 个子节点建立直连流
	Width int32 `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	// 文件元信息（uid/gid/权限/修改时间），首条有效
	Uid     uint32 `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid     uint32 `protobuf:"varint,9,opt,name=gid,proto3" json:"gid,omitempty"`
	Filemod uint32 `protobuf:"varint,10,opt,name=filemod,proto3" json:"filemod,omitempty"`
	Modtime int64  `protobuf:"varint,11,opt,name=modtime,proto3" json:"modtime,omitempty"`
	// 来源节点标识（可选，日志追踪用）
	SourceNode string `protobuf:"bytes,12,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
}

func (x *PutStreamReq) Reset() {
	*x = PutStreamReq{}
	mi := &file_internal_distree_proto_distree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStreamReq) ProtoMessage() {}

func (x *PutStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_distree_proto_distree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStreamReq.ProtoReflect.Descriptor instead.
func (*PutStreamReq) Descriptor() ([]byte, []int) {
	return file_internal_distree_proto_distree_proto_rawDescGZIP(), []int{0}
}

func (x *PutStreamReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PutStreamReq) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *PutStreamReq) GetDestDir() string {
	if x != nil {
		return x.DestDir
	}
	return ""
}

func (x *PutStreamReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PutStreamReq) GetNodelist() string {
	if x != nil {
		return x.Nodelist
	}
	return ""
}

func (x *PutStreamReq) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *PutStreamReq) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PutStreamReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PutStreamReq) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *PutStreamReq) GetFilemod() uint32 {
	if x != nil {
		return x.Filemod
	}
	return 0
}

func (x *PutStreamReq) GetModtime() int64 {
	if x != nil {
		return x.Modtime
	}
	return 0
}

func (x *PutStreamReq) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

// PutStreamReply 是服务端（包括下游递归）返回给上游的结果条目。
// 客户端可收到多条 Reply，每条对应一个节点或一批节点。
type PutStreamReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 该条回复对应的节点列表（可为单节点或 nodeset 表达式）
	Nodelist string `protobuf:"bytes,2,opt,name=nodelist,proto3" json:"nodelist,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PutStreamReply) Reset() {
	*x = PutStreamReply{}
	mi := &file_internal_distree_proto_distree_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutStreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutStreamReply) ProtoMessage() {}

func (x *PutStreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_distree_proto_distree_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutStreamReply.ProtoReflect.Descriptor instead.
func (*PutStreamReply) Descriptor() ([]byte, []int) {
	return file_internal_distree_proto_distree_proto_rawDescGZIP(), []int{1}
}

func (x *PutStreamReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PutStreamReply) GetNodelist() string {
	if x != nil {
		return x.Nodelist
	}
	return ""
}

func (x *PutStreamReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_distree_proto_distree_proto protoreflect.FileDescriptor

var file_internal_distree_proto_distree_proto_rawDesc = []byte{
	0x0a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x65, 0x22,
	0xa2, 0x02, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x64,
	0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74, 0x44, 0x69,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x6d, 0x6f, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x6d, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x56, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4b, 0x0a, 0x08,
	0x44, 0x69, 0x73, 0x74, 0x54, 0x72, 0x65, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x15, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x65, 0x2e,
	0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x65, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x2d, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_distree_proto_distree_proto_rawDescOnce sync.Once
	file_internal_distree_proto_distree_proto_rawDescData = file_internal_distree_proto_distree_proto_rawDesc
)

func file_internal_distree_proto_distree_proto_rawDescGZIP() []byte {
	file_internal_distree_proto_distree_proto_rawDescOnce.Do(func() {
		file_internal_distree_proto_distree_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_distree_proto_distree_proto_rawDescData)
	})
	return file_internal_distree_proto_distree_proto_rawDescData
}

var file_internal_distree_proto_distree_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_distree_proto_distree_proto_goTypes = []any{
	(*PutStreamReq)(nil),   // 0: distree.PutStreamReq
	(*PutStreamReply)(nil), // 1: distree.PutStreamReply
}
var file_internal_distree_proto_distree_proto_depIdxs = []int32{
	0, // 0: distree.DistTree.PutStream:input_type -> distree.PutStreamReq
	1, // 1: distree.DistTree.PutStream:output_type -> distree.PutStreamReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_distree_proto_distree_proto_init() }
func file_internal_distree_proto_distree_proto_init() {
	if File_internal_distree_proto_distree_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_distree_proto_distree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_distree_proto_distree_proto_goTypes,
		DependencyIndexes: file_internal_distree_proto_distree_proto_depIdxs,
		MessageInfos:      file_internal_distree_proto_distree_proto_msgTypes,
	}.Build()
	File_internal_distree_proto_distree_proto = out.File
	file_internal_distree_proto_distree_proto_rawDesc = nil
	file_internal_distree_proto_distree_proto_goTypes = nil
	file_internal_distree_proto_distree_proto_depIdxs = nil
}
