// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: internal/distree/proto/distree.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistTree_PutStream_FullMethodName = "/distree.DistTree/PutStream"
)

// DistTreeClient is the client API for DistTree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DistTree 是面向超算集群依赖分发的树形传输服务。
// 每次 PutStream 调用对应一个文件的完整推送（一轮）；
// 多文件时客户端依次发起多轮调用（多轮对话语义）。
type DistTreeClient interface {
	// PutStream: 客户端流式发送文件块，服务端流式回传各节点的执行结果。
	PutStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PutStreamReq, PutStreamReply], error)
}

type distTreeClient struct {
	cc grpc.ClientConnInterface
}

func NewDistTreeClient(cc grpc.ClientConnInterface) DistTreeClient {
	return &distTreeClient{cc}
}

func (c *distTreeClient) PutStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PutStreamReq, PutStreamReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DistTree_ServiceDesc.Streams[0], DistTree_PutStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutStreamReq, PutStreamReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistTree_PutStreamClient = grpc.BidiStreamingClient[PutStreamReq, PutStreamReply]

// DistTreeServer is the server API for DistTree service.
// All implementations must embed UnimplementedDistTreeServer
// for forward compatibility.
//
// DistTree 是面向超算集群依赖分发的树形传输服务。
// 每次 PutStream 调用对应一个文件的完整推送（一轮）；
// 多文件时客户端依次发起多轮调用（多轮对话语义）。
type DistTreeServer interface {
	// PutStream: 客户端流式发送文件块，服务端流式回传各节点的执行结果。
	PutStream(grpc.BidiStreamingServer[PutStreamReq, PutStreamReply]) error
	mustEmbedUnimplementedDistTreeServer()
}

// UnimplementedDistTreeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistTreeServer struct{}

func (UnimplementedDistTreeServer) PutStream(grpc.BidiStreamingServer[PutStreamReq, PutStreamReply]) error {
	return status.Errorf(codes.Unimplemented, "method PutStream not implemented")
}
func (UnimplementedDistTreeServer) mustEmbedUnimplementedDistTreeServer() {}
func (UnimplementedDistTreeServer) testEmbeddedByValue()                  {}

// UnsafeDistTreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistTreeServer will
// result in compilation errors.
type UnsafeDistTreeServer interface {
	mustEmbedUnimplementedDistTreeServer()
}

func RegisterDistTreeServer(s grpc.ServiceRegistrar, srv DistTreeServer) {
	// If the following call pancis, it indicates UnimplementedDistTreeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistTree_ServiceDesc, srv)
}

func _DistTree_PutStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DistTreeServer).PutStream(&grpc.GenericServerStream[PutStreamReq, PutStreamReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DistTree_PutStreamServer = grpc.BidiStreamingServer[PutStreamReq, PutStreamReply]

// DistTree_ServiceDesc is the grpc.ServiceDesc for DistTree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistTree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distree.DistTree",
	HandlerType: (*DistTreeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutStream",
			Handler:       _DistTree_PutStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/distree/proto/distree.proto",
}
